import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { createClient } from "@supabase/supabase-js";

function getSupabaseUrl() {
  let url = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
  return url.replace(/\/rest\/v1\/?$/, "").replace(/\/+$/, "");
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: "#ffffff",
    fontFamily: "Helvetica",
  },
  header: {
    fontSize: 24,
    marginBottom: 20,
    color: "#18181b",
    fontWeight: "bold",
  },
  section: {
    marginBottom: 10,
  },
  content: {
    fontSize: 12,
    lineHeight: 1.6,
    color: "#3f3f46",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 10,
    color: "#a1a1aa",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#e4e4e7",
    paddingTop: 10,
  },
});

function ReportDocument({ title, content }: { title: string; content: string }) {
  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      React.createElement(Text, { style: styles.header }, title),
      React.createElement(
        View,
        { style: styles.section },
        React.createElement(Text, { style: styles.content }, content)
      ),
      React.createElement(
        Text,
        { style: styles.footer },
        `Generated by ChatAgent · ${new Date().toLocaleDateString()}`
      )
    )
  );
}

export async function generatePdfReport(title: string, content: string, userId: string): Promise<string> {
  try {
    const doc = React.createElement(ReportDocument, { title, content });
    const buffer = await renderToBuffer(doc as any);

    const supabaseUrl = getSupabaseUrl();
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";
    const supabase = createClient(supabaseUrl, supabaseKey);

    const fileName = `report_${userId}_${Date.now()}.pdf`;

    // Attempt to upload to Supabase Storage bucket 'reports'
    const { data, error } = await supabase.storage
      .from("reports")
      .upload(fileName, buffer, {
        contentType: "application/pdf",
        upsert: true,
      });

    if (!error && data) {
      const { data: publicUrlData } = supabase.storage.from("reports").getPublicUrl(fileName);
      return publicUrlData.publicUrl;
    }

    console.warn("Supabase storage upload error, returning base64 data URL fallback:", error);
    return `data:application/pdf;base64,${buffer.toString("base64")}`;
  } catch (err: any) {
    console.error("PDF generation error:", err);
    throw new Error(`Failed to generate PDF report: ${err.message}`);
  }
}
